### ISSUE TITLE
histogram.cpp

### ISSUE THREAD

**Issue by newsages** [openalpr/openalpr#328] opened 2016-04-21 14:57 UTC
LINE :   bool isOn = histoImg.at<uchar>(histoImg.rows - 1 - yOffset, col);

Bug?

**Comment by matthill** [comment] 2016-04-22 17:14
Not sure, what do you see that looks suspicious?

That portion of the code is looking at the histogram image to measure the possible character areas.  In the picture below, the left pane shows the histogram , the code is tracing along the X-axis to find blocks of white.  The end result is the x coordinates on the right-pane that map to character locations.

![histo](https://cloud.githubusercontent.com/assets/508260/14749160/f7724e26-088b-11e6-85d2-004c237afc15.png)

**Comment by newsages** [comment] 2016-04-24 00:11
I have some randoms crash on runtime (linux g++5 )  ,cast  bool for int/double/float.

in CV docs say:
cv::Mat::at Returns a reference to the specified array element.

Note that the variants with a single index (i) can be used to access elements of single-row or single-column 2-dimensional arrays. That is, if, for example, A is a 1 x N floating-point matrix and B is an M x 1 integer matrix, you can simply write A.at<float>(k+4) and B.at<int>(2*i+1) instead of A.at<float>(0,k+4) and B.at<int>(2*i+1,0) , respectively.

The example below initializes a Hilbert matrix:
Mat H(100, 100, CV_64F);
for(int i = 0; i < H.rows; i++)
    for(int j = 0; j < H.cols; j++)
        H.at<double>(i,j)=1./(i+j+1);

**Comment by matthill** [comment] 2016-04-24 13:33
When you run with the debugger, you see that line of code is causing crashing?  That would surprise me.  On what system/platform are you seeing crashing?  I have a handful of test systems on 64-bit Ubuntu 14.04 that have been running alprd v2.2 for months without crashes.  Any spurious crashing (even if rare) is something I definitely would like to fix.

It's a CV_8U image type (i.e., single-channel grayscale with integer values between 0-255) We could be more explicit and change it to:
histoImg.at<int>(histoImg.rows - 1 - yOffset, col);

although I think it should be the same thing.

Can you try running your program under gdb (flip this first: https://github.com/openalpr/openalpr/blob/master/src/CMakeLists.txt#L3) 

to get a stacktrace?

Alternatively, a coredump and the compiled binary (w/ debug symbols) would be equally useful.

**Comment by newsages** [comment] 2016-04-25 05:56
Yea.
I use 14.04 to and toolchains-r/test g++5.

Gdb say this line in qtcreator. I make a warpper for qt.

Now i testing in16.04 and g++6.

**Comment by matthill** [comment] 2016-04-25 14:33
I just took a look at the code to make the fix, and noticed it was already cast and seems to always have been:
https://github.com/openalpr/openalpr/blob/master/src/openalpr/segmentation/histogram.cpp#L235

Are you sure this is your issue?

**Comment by newsages** [comment] 2016-04-25 17:20
yes, 235.
 bool isOn = histoImg.at<uchar>(histoImg.rows - 1 - yOffset, col);

**Comment by matthill** [comment] 2016-04-25 17:24
Oh, I see.  The code appears to be correct as-is (cast to a uchar).  GitHub just filtered out your greater_than and less_than signs:

    bool isOn = histoImg.at<uchar>(histoImg.rows - 1 - yOffset, col);

Whatever error you're running into, I don't think this is the cause.

**Comment by newsages** [comment] 2016-04-25 17:31
Yes git filter '<>'

I will make more test and wait for crash in debug for get trace.

**Comment by karelvorechovsky** [comment] 2016-05-06 12:40
I ran into this crash too, today built debug and walked till
`bool isOn = histoImg.at<uchar>(histoImg.rows - 1 - yOffset, col);`
where Mat.at() is called with (-1 , 13)

It seems like the cols and rows are swapped?

**Comment by matthill** [comment] 2016-05-06 13:02
Excellent, thanks for finding that.

Do you have the input image that causes the crash?  We could clamp the rows to 0 in the case where it's negative, but I'm wondering what is causing the negative value upstream.

**Comment by karelvorechovsky** [comment] 2016-05-06 13:17
You walk the histogram to score the rows by:
for(rows)

**Comment by karelvorechovsky** [comment] 2016-05-06 13:21
When scoring the rows of LP histogram:

for(rows)
  i++
  for(cols)
    j++
    histogram.at(rows **-1** -i, j)

This code will produce out of range access for any hit.

**Comment by newsages** [comment] 2016-05-06 13:35
Right!!

**Comment by karelvorechovsky** [comment] 2016-05-06 17:49
The
`HistogramVertical::HistogramVertical(Mat inputImage, Mat mask)`
constructor calls
`analyzeImage(inputImage, mask, true);`
which changes the histogram image header and data you merged from the previous tresholded characters. I believe this is the bug, since in the next scanning for loop, the code refers to the original histoImg Mat (but the histogram passed as an argument has already a different one).

**Comment by matthill** [comment] 2016-05-06 20:47
Thanks, that sounds right.  I applied the above fix, please let me know if that resolves it for you.

**Comment by karelvorechovsky** [comment] 2016-05-06 21:59
Thx for quick response. Yes, that should probably solve it.
Just for clarification, the `std::vector<int> colHeights;` basicly contains the histogram itself if I understand it correctly.

I want to refactor the code to avoid the unnecessary executed code in the constructor.

**Closed** 2016-05-06 23:26 UTC
