### ISSUE TITLE
Tilted Plate

### ISSUE THREAD

**Issue by LordF** [openalpr/openalpr#88] opened 2015-03-11 15:28 UTC
Hello,
I've noticed that when plate region is tilted relative to the camera, the system fails completely. I think the problem might be in the character analysis phase, since the plate still has not been corrected(deskewed) and char boxes are not detected. I think maybe if tilt correction comes earlier it might help.

**Comment by matthill** [comment] 2015-03-12 00:43
Can you upload a couple example images?  That will help determine what the cause might be.  There is a maximum rotation attribute in the config -- it helps reduce false positives.

**Comment by LordF** [comment] 2015-03-12 12:48
![1](https://cloud.githubusercontent.com/assets/5480314/6617832/ac9bd182-c89b-11e4-83a5-4dc42b584206.jpg)
In the image you can see how the plate has perspective distortion, so the system can't detect char boxes and character analysis phase fails. By correcting the distortion previously the system is able to detect the boxes. In the cropped plate region it is possible to correct tilt by major axis of the plate rectangle and correct it before character analysis.
![image](https://cloud.githubusercontent.com/assets/5480314/6617928/a446a934-c89c-11e4-8e9f-fc70ae2eb483.png)

**Comment by matthill** [comment] 2015-03-13 03:42
Do you think this is related to this issue: https://github.com/openalpr/openalpr/issues/84

Or is it something different?

**Comment by LordF** [comment] 2015-03-13 12:22
I think it may be related. From some prior testing I found that when the
plate rectangle is approximately straight the system works quite good. With
plates from my dataset some are skewed since the camera is not
perpendicular in relation to the plate(most of them the camera is located
beside the vehicle), so character analysis phase returns a confidence of
zero, since each character aspect is distorted and heuristics rules fails.
The solution I found is the same you gave, I try to estimate the plate
rectangle inclination angle and correct it before moving on, so the
detection improved. From what I could understand, currently the system
tries to find char boxes in the plate region and then correct plate skew
afterwards.

2015-03-13 0:42 GMT-03:00 Matthew Hill <notifications@github.com>:

**Comment by matthill** [comment] 2015-03-13 13:15
Yes, I'm definitely open to ideas if there's a better way of doing it.

Right now the character analysis phase is mostly a filter that is required before moving forward in the process.  Given a detected region (which may or may not be a license plate) it looks for a parallel row of letters (blobs) that are about the same size.  

If it detects it, subsequent phases will try and find the plate edges.  The edge lines are used to correct the plate perspective before moving on to character segmentation (cropping out each individual character) and then OCR (figuring out what each character is).

**Comment by LordF** [comment] 2015-03-13 13:30
I would suggest finding each detected plate rectangle skew angle and
correcting before character analysis in order to improve overall detection(
I think moments would fit in nice here). I will try to come up with some
ideas and post some code.

2015-03-13 10:15 GMT-03:00 Matthew Hill <notifications@github.com>:

**Comment by matthill** [comment] 2015-07-04 15:32
Should be resolved by the recently added camera calibration utility

**Closed by matthill** 2015-07-04 15:32 UTC
